repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.22
  hooks:
    - id: tflint
      args:
        - "--module"
        - "--config=.tflint.hcl"
    - id: terraform-validate
    - id: terraform-fmt
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.80.0
  hooks:
    - id: terraform_tfsec
    - id: terraform_docs